# Generated by Django 5.2.16 on 2026-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_booking_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screen',
            name='total_seats',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
